const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const FETCH_TRENDING_MOVIE = "FETCH_TRENDING_MOVIE";
const FETCH_POPULAR_MOVIE = "FETCH_POPULAR_MOVIE";
const FETCH_TOP_RATED_MOVIE = "FETCH_TOP_RATED_MOVIE";
const FETCH_UPCOMING_MOVIE = "FETCH_UPCOMING_MOVIE";
const FETCH_MOVIE_GENRE = "FETCH_MOVIE_GENRE";
const FETCH_MOVIE_CERTIFICATIONS = "FETCH_MOVIE_CERTIFICATIONS";
const FETCH_FILTER = "FETCH_FILTER";
const FETCH_PEOPLE = "FETCH_PEOPLE";
const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";
const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";
const FETCH_MOVIE_VIDEOS = "FETCH_MOVIE_VIDEOS";
const FETCH_MOVIE_IMAGES = "FETCH_MOVIE_IMAGES";
const FETCH_WATCH_PROVIDERS = "FETCH_WATCH_PROVIDERS";
const SET_ISLOADING_TRUE = "SET_ISLOADING_TRUE,";
const SET_ISLOADING_FALSE = "SET_ISLOADING_TRUE";

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  FETCH_TRENDING_MOVIE,
  FETCH_POPULAR_MOVIE,
  FETCH_TOP_RATED_MOVIE,
  FETCH_UPCOMING_MOVIE,
  FETCH_MOVIE_GENRE,
  FETCH_MOVIE_CERTIFICATIONS,
  FETCH_FILTER,
  FETCH_PEOPLE,
  FETCH_MOVIE_DETAIL,
  FETCH_MOVIE_CREDITS,
  FETCH_MOVIE_VIDEOS,
  FETCH_MOVIE_IMAGES,
  FETCH_WATCH_PROVIDERS,
  SET_ISLOADING_TRUE,
  SET_ISLOADING_FALSE,
};
